<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>micipsa_perception</name>
  <version>1.0.0</version>
  <description>Provides perception capabilities for Micipsa, processing camera and sensor data into structured outputs</description>
  <maintainer email="yousriouartsi@gmail.com">yousri</maintainer>
  <license>TODO: License declaration</license>

  <!-- ============ -->
  <!-- Build System -->
  <!-- ============ -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ================== -->
  <!-- Build Dependencies -->
  <!-- ================== -->

  <!-- Pointcloud Processing Deps -->
  <build_depend>pcl_conversions</build_depend>
  <build_depend>pcl_ros</build_depend>
  <build_export_depend>pcl_conversions</build_export_depend>
  <build_export_depend>pcl_ros</build_export_depend>

  <!-- Apriltags Detection Deps -->
  <build_depend>apriltag_msgs</build_depend>

  <depend>micipsa_msgs</depend>

  <!-- ==================== -->
  <!-- Runtime Dependencies -->
  <!-- ==================== -->

  <!-- Pointcloud Processing Deps -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_sensor_msgs</exec_depend>
  <exec_depend>pcl_ros</exec_depend>

  <!-- Apriltags Detection Deps -->
  <exec_depend>apriltag_ros</exec_depend>
  <exec_depend>apriltag_msgs</exec_depend>

  <!-- ================= -->
  <!-- Test Dependencies -->
  <!-- ================= -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
